version: '3.3'
services:
  mysql:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    restart: always
    environment:
      MYSQL_DATABASE: 'travels'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      #- ./db:/var/lib/mysql
      - my-db:/var/lib/mysql

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile  #сборка из докер файла
    depends_on: [mysql]   #установка зависимости
    ports:
      - 80:80

# Names our volume
volumes:
  my-db:
