// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type visitTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *visitTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("visit").
func (v *visitTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *visitTableType) Columns() []string {
	return []string{"id", "location", "user", "visited_at", "mark"}
}

// NewStruct makes a new struct for that view or table.
func (v *visitTableType) NewStruct() reform.Struct {
	return new(Visit)
}

// NewRecord makes a new record for that table.
func (v *visitTableType) NewRecord() reform.Record {
	return new(Visit)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *visitTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// VisitTable represents visit view or table in SQL database.
var VisitTable = &visitTableType{
	s: parse.StructInfo{Type: "Visit", SQLSchema: "", SQLName: "visit", Fields: []parse.FieldInfo{{Name: "Id", Type: "uint32", Column: "id"}, {Name: "Location", Type: "uint32", Column: "location"}, {Name: "User", Type: "uint32", Column: "user"}, {Name: "Visited_at", Type: "time.Time", Column: "visited_at"}, {Name: "Mark", Type: "uint", Column: "mark"}}, PKFieldIndex: 0},
	z: new(Visit).Values(),
}

// String returns a string representation of this struct or record.
func (s Visit) String() string {
	res := make([]string, 5)
	res[0] = "Id: " + reform.Inspect(s.Id, true)
	res[1] = "Location: " + reform.Inspect(s.Location, true)
	res[2] = "User: " + reform.Inspect(s.User, true)
	res[3] = "Visited_at: " + reform.Inspect(s.Visited_at, true)
	res[4] = "Mark: " + reform.Inspect(s.Mark, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Visit) Values() []interface{} {
	return []interface{}{
		s.Id,
		s.Location,
		s.User,
		s.Visited_at,
		s.Mark,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Visit) Pointers() []interface{} {
	return []interface{}{
		&s.Id,
		&s.Location,
		&s.User,
		&s.Visited_at,
		&s.Mark,
	}
}

// View returns View object for that struct.
func (s *Visit) View() reform.View {
	return VisitTable
}

// Table returns Table object for that record.
func (s *Visit) Table() reform.Table {
	return VisitTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Visit) PKValue() interface{} {
	return s.Id
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Visit) PKPointer() interface{} {
	return &s.Id
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Visit) HasPK() bool {
	return s.Id != VisitTable.z[VisitTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Visit) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.Id = uint32(i64)
	} else {
		s.Id = pk.(uint32)
	}
}

// check interfaces
var (
	_ reform.View   = VisitTable
	_ reform.Struct = (*Visit)(nil)
	_ reform.Table  = VisitTable
	_ reform.Record = (*Visit)(nil)
	_ fmt.Stringer  = (*Visit)(nil)
)

func init() {
	parse.AssertUpToDate(&VisitTable.s, new(Visit))
}
